//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_20190624.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tComment
    {
        public int Id { get; set; }
        [DisplayName("姓名")]
        [Required]
        public string Name { get; set; }
        [DisplayName("電子信箱")]
        [EmailAddress]
        public string Email { get; set; }
        [DisplayName("連絡電話")]
        [Required]
        public string Phone { get; set; }
        [DisplayName("留言")]
        [Required]
        public string Message { get; set; }
        [DisplayName("留言日期")]
        [Required]
        public Nullable<System.DateTime> CommentDate { get; set; }
        public string Image { get; set; }
    }
}
