//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_20190624.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tIG
    {
        public int Id { get; set; }
        [DisplayName("文章內容")]
        public string IgContent { get; set; }
        [DisplayName("圖片連結")]
        public string IgSrc { get; set; }
        [DisplayName("發文日期")]
        public string IgDate { get; set; }
        [DisplayName("文章連結")]
        public string IgLink { get; set; }
    }
}
