//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_20190624.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tMember
    {
        public int Id { get; set; }
        [DisplayName("信箱(即為會員帳號)")]
        [Required(ErrorMessage = "信箱不可空白")]
        [EmailAddress]
        public string email { get; set; }
        [DisplayName("設定密碼")]
        [Required(ErrorMessage = "密碼不可空白")]
        public string pwd { get; set; }
        [DisplayName("確認密碼")]
        [Required(ErrorMessage = "請再確認一次密碼")]
        public string repwd { get; set; }
        [DisplayName("中文姓名")]
        public string userName { get; set; }
        [DisplayName("生日")]
        public Nullable<System.DateTime> birthDay { get; set; }
    }
}
