//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_20190624.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tOrderDetail
    {
        public int Id { get; set; }
        [DisplayName("訂單編號")]
        public string OrderGuid { get; set; }
        [DisplayName("中文姓名")]
        public string userName { get; set; }
        [DisplayName("商品名稱")]
        public string pName { get; set; }
        [DisplayName("商品價格")]
        public Nullable<int> pPrice { get; set; }
        [DisplayName("訂購數量")]
        public Nullable<int> pQty { get; set; }
        [DisplayName("是否為訂單")]
        public string isApprove { get; set; }
        [DisplayName("收件人")]
        public string recName { get; set; }
        [DisplayName("收件地址")]
        public string address { get; set; }
        [DisplayName("訂單日期")]
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
